options:
  - tv
  - ttyrec
  - log
  - game
  - graph
  - random

reserved-names:
  - '/='
  - '='
  - '<=>'
  - '<='
  - '>='
  - '<'
  - '>'
  - '+'
  - '-'
  - '*'
  - '/'
  - mod
  - float
  - int
  - str
  - and
  - or

operators:
  - op: or
    negated: and
    argtype: '!'
    result: '!'
    display_string: ' || '
    precedence: 1

  - op: and
    negated: or
    argtype: '!'
    result: '!'
    display_string: ' '
    precedence: 2

  - op: not
    negated: and
    argtype: '!'
    result: '!'
    display_string: '!'
    arity: 1
    precedence: 100

  - op: is
    display_string: '=:'
    negated: is_not
    argtype: '*'
    result: '!'
    arity: 2
    precedence: 40

  - op: is_not
    display_string: '!=:'
    negated: is
    argtype: '*'
    result: '!'
    arity: 2
    precedence: 40

  - op: '='
    negated: '!='
    argtype: '*'
    result: '!'
    arity: 2
    precedence: 40

  - op: '!='
    negated: '='
    argtype: '*'
    result: '!'
    arity: 2
    precedence: 40

  - op: '=='
    negated: '!=='
    argtype: '*'
    result: '!'
    arity: 2
    sql_operator: '='
    precedence: 40

  - op: '!=='
    negated: '=='
    argtype: '*'
    result: '!'
    arity: 2
    sql_operator: '!='
    precedence: 40

  - op: '=~'
    negated: '!~'
    argtype: S
    result: '!'
    arity: 2
    non_commutative: true
    sql_operator: ' ILIKE '
    precedence: 40

  - op: '!~'
    negated: '=~'
    argtype: S
    result: '!'
    arity: 2
    non_commutative: true
    sql_operator: ' NOT ILIKE '
    precedence: 40

  - op: '~~'
    negated: '!~~'
    argtype: S
    result: '!'
    arity: 2
    non_commutative: true
    sql_operator: '~*'
    precedence: 40

  - op: '!~~'
    negated: '~~'
    argtype: S
    result: '!'
    arity: 2
    non_commutative: true
    sql_operator: '!~*'
    precedence: 40

  - op: '<'
    negated: '>='
    argtype: '*'
    result: '!'
    arity: 2
    non_commutative: true
    precedence: 40
    relational: true

  - op: '>='
    negated: '<'
    argtype: '*'
    result: '!'
    arity: 2
    non_commutative: true
    precedence: 40
    relational: true

  - op: '>'
    negated: '<='
    argtype: '*'
    result: '!'
    arity: 2
    non_commutative: true
    precedence: 40
    relational: true

  - op: '<='
    negated: '>'
    argtype: '*'
    result: '!'
    arity: 2
    non_commutative: true
    precedence: 40
    relational: true

  - op: '+'
    argtype: I
    result: I
    precedence: 60

  - op: '-'
    argtype: I
    result: I
    arity: 2
    precedence: 60
    non_commutative: true

  - op: '*'
    argtype: F
    result: F
    precedence: 80

  - op: '/'
    argtype: I
    result: F
    precedence: 80
    non_commutative: true

  - op: '%'
    argtype: I
    result: I
    arity: 2
    precedence: 80

  - op: '**'
    sql_operator: '^'
    argtype: F
    result: F
    arity: 2
    precedence: 90
