options:
  - tv
  - ttyrec
  - log
  - game

operators:
  - op: and
    negated: or
    argtype: '!'
    result: '!'
    display_string: ' '

  - op: or
    negated: and
    argtype: '!'
    result: '!'
    display_string: ' || '

  - op: not
    negated: and
    argtype: '!'
    result: '!'
    display_string: '!'
    arity: 1

  - op: '='
    negated: '!='
    argtype: '*'
    result: '!'
    arity: 2

  - op: '!='
    negated: '='
    argtype: '*'
    result: '!'
    arity: 2

  - op: '=='
    negated: '!=='
    argtype: '*'
    result: '!'
    arity: 2
    sql_operator: '='

  - op: '!=='
    negated: '=='
    argtype: '*'
    result: '!'
    arity: 2
    sql_operator: '!='

  - op: '=~'
    negated: '!~'
    argtype: S
    result: '!'
    arity: 2
    non_commutative: true
    sql_operator: ' ILIKE '

  - op: '!~'
    negated: '=~'
    argtype: S
    result: '!'
    arity: 2
    non_commutative: true
    sql_operator: ' NOT ILIKE '

  - op: '~~'
    negated: '!~~'
    argtype: S
    result: '!'
    arity: 2
    non_commutative: true
    sql_operator: '~*'

  - op: '!~~'
    negated: '~~'
    argtype: S
    result: '!'
    arity: 2
    non_commutative: true
    sql_operator: '!~*'

  - op: '<'
    negated: '>='
    argtype: '*'
    result: '!'
    arity: 2
    non_commutative: true

  - op: '>='
    negated: '<'
    argtype: '*'
    result: '!'
    arity: 2
    non_commutative: true

  - op: '>'
    negated: '<='
    argtype: '*'
    result: '!'
    arity: 2
    non_commutative: true

  - op: '<='
    negated: '>'
    argtype: '*'
    result: '!'
    arity: 2
    non_commutative: true
